### ISSUE TITLE
Possible bug in cnv2igv v1.3

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-scripts#18]
I get an error running the latest version on a Battenberg output:

```
python src/lcr-scripts/cnv2igv/1.3/cnv2igv.py --mode battenberg --sample FL2007T2 results/gambl/battenberg-1.1/02-battenberg/genome--grch37/FL2007T2--FL2007N/FL2007T2_subclones.txt

running _battenberg_to_igv_seg for FL2007T2--FL2007N on gphost03.bcgsc.ca at Sat Dec 26 15:23:45 PST 2020
Traceback (most recent call last):
  File "/projects/rmorin/projects/gambl-repos/gambl-rmorin/src/lcr-scripts/cnv2igv/1.3/cnv2igv.py", line 320, in <module>
    main()
  File "/projects/rmorin/projects/gambl-repos/gambl-rmorin/src/lcr-scripts/cnv2igv/1.3/cnv2igv.py", line 317, in main
    print(seg.to_igv(prepend))
  File "/projects/rmorin/projects/gambl-repos/gambl-rmorin/src/lcr-scripts/cnv2igv/1.3/cnv2igv.py", line 251, in to_igv
    return('\t'.join([self.sample, self.chrm, self.start, \
TypeError: sequence item 4: expected str instance, int found
```

**Comment by Kdreval** [comment]
Yes, this was a bug in the script. It was returning 0 for LOH_flag n some segments, and I ensured it will always be a string. I submitted PR for a fix. Thank you for posting the issue with sample ID. I confirmed it runs and IGV representation corresponds to subclones output.
